In [36]:
import numpy as np
import pandas as pd
from pandas._libs.interval import Interval
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
import pickle

This credit scoring model is built on the alternative data. Over 2.5 billion peoples dont have bank accounts and credit history, so traditional approach to calculate the credit score is impossible for them. But, there is a alternative way to calculate the credit score. We can collect the data from this peoples which is not related to the credit or financial data, and feed it to this model to get a credit score. This alternative data of this peoples could be like married status, childrens, education, job, income, relatives, phone call history, SMS history, digital payment history, neighbors, home address, office address, assets, health, and many more

We are using some of this features, like

FEATURES :

Age
Marital Status :

1 - Married, 0 - Not Married

Dependents : Number of dependents (0, 1, 2, 3, 4, 5+)
Total years of work experience : Number of work experience (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10+)
Working Status :

Unemployed - 0, Student - 1, Part-Time - 2, Full-Time - 3

Highest education qualification :

High School - 0, Bachelor's - 1, Master's - 2, Doctorate - 3

Area of study :

Life Sciences - 0, Mathematical Sciences - 1, Humanities - 2, Social Science - 3, Business - 4, Law - 5, Engineering & Technology - 6, Sport - 7

Annual Income
Target -

1 - Good User, 0 - Bad User

In [2]:
#Generating random "alternative data" for credit scoing model

rand_age_data = np.random.randint(21, 100 + 1, 1000)
rand_maritalstatus_data = np.random.randint(0, 1 + 1, 1000)
rand_dependents_data = np.random.randint(0, 20 + 1, 1000)
rand_workexp_data = np.random.randint(0, 50 + 1, 1000)
rand_working_status_data = np.random.randint(0, 3 + 1, 1000)
rand_edu_quali_data = np.random.randint(0, 3 + 1, 1000)
rand_area_study_data = np.random.randint(0, 7 + 1, 1000)
rand_annualinc_data = np.random.randint(0, 100 + 1, 1000) #In thousands

rand_target_data = np.random.randint(0, 1 + 1, 1000)

In [3]:
df_orig = pd.DataFrame({'age':rand_age_data,
                        'marital_status': rand_maritalstatus_data,
                        'dependents' : rand_dependents_data,
                        'work_exp': rand_workexp_data,
                        'work_status': rand_working_status_data,
                        'education_quali': rand_edu_quali_data, 
                        'area_study': rand_area_study_data,
                        'annual_income': rand_annualinc_data,
                        'target' : rand_target_data})
df_orig.head()

age  marital_status  dependents  ...  area_study  annual_income  target
0   73               1          17  ...           7             41       1
1   74               0          19  ...           3             99       0
2   85               1           6  ...           2             55       0
3   70               1           5  ...           6             26       0
4   75               1          20  ...           2             39       1

[5 rows x 9 columns]

## Data Transformations


In [5]:
X = df_orig.drop('target', 1)
y = df_orig.target

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


In [6]:
#Splitting the data into 80:20 ratio of training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
# Scaling 
scaler = StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)



In [11]:
# Using Logistic Regression

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [12]:
X_train_scaled

array([[-1.29055143,  1.02020406,  1.29746746, ..., -0.45484265,
        -0.66551056, -1.22857092],
       [ 0.40782906, -0.98019606,  0.62996008, ...,  1.3376407 ,
         0.61843264,  0.57572726],
       [-1.37764786, -0.98019606,  0.96371377, ..., -1.35108433,
        -0.66551056, -1.47145721],
       ...,
       [ 0.58202193, -0.98019606, -1.03880835, ...,  1.3376407 ,
        -1.09349163, -0.95098658],
       [-1.20345499,  1.02020406, -0.53817782, ...,  1.3376407 ,
        -0.23752949, -1.43675917],
       [-1.55184073, -0.98019606,  1.4643443 , ...,  1.3376407 ,
         1.04641371, -1.15917483]])

In [ ]:
# The score for each set of features can be calculated:
score = 101.88 + 28.85 * ln_odds
score

89.90726876424628

In [23]:
pred=model.predict(X_train_scaled)

In [24]:
pred

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,

In [25]:
X_test=np.array(X_test)

In [34]:
a=np.expand_dims(X_train_scaled[1],axis=0)
pred2=model.predict(a)

In [35]:
pred2

array([1])

In [37]:
pickle.dump(model, open('model.pkl', 'wb'))